################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
ICallBLE/ble_user_config.obj: C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/icall/app/ble_user_config.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs730/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" --cmd_file="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/TOOLS/defines/ble5_project_zero_cc26x2r1lp_app_FlashROM_Debug.opt" --cmd_file="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/config/build_components.opt" --cmd_file="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/config/factory_config.opt" --cmd_file="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_stack_library/TOOLS/build_config.opt"  -mv7M4 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app" --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/Application" --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/Startup" --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/PROFILES" --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/Include" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/controller/cc26xx/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/rom" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/common/cc26xx" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/icall/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/target" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/hal/src/target/_common" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/hal/src/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/heapmgr" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/icall/src/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/osal/src/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/services/src/saddr" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/services/src/sdata" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/devices/cc13x2_cc26x2" --include_path="C:/ti/ccs730/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --define=DeviceFamily_CC26X2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICallBLE/ble_user_config.d_raw" --obj_directory="ICallBLE" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ICallBLE/icall_api_lite.obj: C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/icall/app/icall_api_lite.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs730/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" --cmd_file="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/TOOLS/defines/ble5_project_zero_cc26x2r1lp_app_FlashROM_Debug.opt" --cmd_file="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/config/build_components.opt" --cmd_file="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/config/factory_config.opt" --cmd_file="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_stack_library/TOOLS/build_config.opt"  -mv7M4 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app" --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/Application" --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/Startup" --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/PROFILES" --include_path="C:/Users/edelmm2/GitHub/Agama/ble5_project_zero_cc26x2r1lp_app/Include" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/controller/cc26xx/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/rom" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/common/cc26xx" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/icall/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/target" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/hal/src/target/_common" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/hal/src/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/heapmgr" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/icall/src/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/osal/src/inc" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/services/src/saddr" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/ble5stack/services/src/sdata" --include_path="C:/ti/simplelink_cc26x2_sdk_1_60_00_04_eng/source/ti/devices/cc13x2_cc26x2" --include_path="C:/ti/ccs730/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --define=DeviceFamily_CC26X2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICallBLE/icall_api_lite.d_raw" --obj_directory="ICallBLE" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


